# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaa3f7195af6fd86396612fd062ebd56bf5a0bd993176cf790bbb41708e766a06715d0bcefdd4dba3ec7d76ff403caf2d94d7da0d6dac210188f58e8dd343933

test:
  secret_key_base: 9cfd611db64afcd4af6c2a98695ab71c943269114dc419baecaf1de398f7cf090c0b3fecaf862b144b002e9f54ff4f1f2d7d647e5812a0e131d31d82fa0c6a96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
